### ISSUE TITLE
does not work with Ubuntu 14.04, AMD drivers 15.x

### ISSUE THREAD

**Issue by kenshirothefist** [epixoip/od6config#6]
Hi,

Just tried this on Ubuntu 14.04, AMD drivers 15.x:

fglrx-updates -- 2:15.200-0ubuntu0.5 -- amd64 -- Video driver for the AMD graphics accelerators

~/build/adl/od6config$ ./od6config --list
No Overdrive6 devices found!

I have two AMD cards in the system:

$ aticonfig --list-adapters
* 0. 01:00.0 AMD Radeon HD 7900 Series  
  1. 02:00.0 AMD Radeon R9 200 Series

The first is 7950 Tahiti, the second is 290x Hawaii.

What could be the issue? Drivers 15.x? Something else?

Thanks!

**Comment by epixoip** [comment]
The 7950 is not an Overdrive6 device, it is Overdrive5. And if your 290X is OEM design and not reference design, it may not implement Overdrive6 properly (this is quite common.) So the issue might simply be the fact that you truly do not have any Overdrive6 devices.

If your 290X is reference design, then you may just have a configuration problem. Are you running X11? Is xorg.conf configured properly? Do you have X authority?

fglrx 15.x definitely isn't the problem, but Ubuntu's package might be.

**Comment by kenshirothefist** [comment]
I'm aware of 7950 not being supported, I'd like to manage the 290x. It's this one: http://www.gigabyte.com/products/product-page.aspx?pid=4885#ov - I guess this is non-reference design?

Do you have any other solution for managing non-reference 290(x) cards? If possible, with voltage control?

Thanks!

**Comment by epixoip** [comment]
Yes, that's a non-reference design card, and may not truly be an Overdrive6/PowerTune 2.0 device. Many OEMs simply took their existing 7970 boards and slapped a 290X chip on it. No, I don't have a solution for these cards. Many of them are ultimately unmanageable (board doesn't support Overdrive6, chip doesn't support Overdrive5.) I don't know if yours falls into this category or not.

**Comment by kenshirothefist** [comment]
Bwah, those newer AMD cards are really bad designed and the management software for GPUs from AMD sucks even more :( ... NVIDIA has such a beautiful tool (nvidia-smi) which works on any card, any manufacturer .... -1 for AMD. Anyway, thanks for your efforts on this tool, and if you find some additional solutions please reply here. Keep up the good work!

**Comment by epixoip** [comment]
Yeah, we stopped offering AMD GPUs last year and are 100% Nvidia now. Life is so much better :)
